name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # nécessaire pour actions-gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (if any)
        run: npm ci

      - name: Build (placeholder)
        run: |
          # Si vous avez un build step (webpack/vite) remplacez cette ligne par "npm run build"
          echo "No build step defined — deploying repository root"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./   # publie la racine du repo (index.html à la racine)